name: CVE2 Task
description: Create a CVE2 Project Task
title: "[TASK] <title>"
labels: ["task"]
body:
- type: textarea
  attributes:
    label: Task Description
    description: A concise description of what needs to be done
  validations:
    required: true
- type: textarea
  attributes:
    label: Description of Done
    description: What are the criteria for completion of this task?
  validations:
    required: true
- type: textarea
  attributes:
    label: Associated PRs
    description: Use this area to provide a link to PRs used to complete this task.
- type: markdown
  attributes:
    value: |
      **Keep task progress up to date by adding comments to the task as it progresses.**
